### ISSUE TITLE
function createCoin() should not be allowed to be called more than once

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/gifto-contracts#4]
We recommend adding a modifier so that createCoin() cannot be called by anybody more than once.

This ensures that the total supply cannot be increased anymore than what is originally minted.

https://github.com/gifto-io/GiftoSmartContract/blob/master/CMultisigWallet_Gifto.sol#L805

**Comment by matt-lough** [comment]
https://github.com/gifto-io/GiftoSmartContract/commit/63108870b6c7136afd1ce1453e6d6201e471c12c
